---
- name: Install packages
  yum: name={{ item }} state=present
  with_items:
    - MySQL-python
    - mariadb-server 

- name: Start mariadb
  service: name=mariadb state=started enabled=yes

- name: Disable firewalld
  service: name=firewalld state=stopped enabled=no