# This playbook deploys the whole application stack in this site.


- name: Load external variables
  hosts: localhost
  connection: local
  gather_facts: no
   
  vars_files:
    - vars/application-config.yml
    
  roles:
    - common
    - setup-hosts

- name: setup db
  hosts: dbservers
  become: yes
  
  vars_files:
    - vars/application-config.yml

  roles:
    - { role: common, become: no }
    - mariadb

- name: setup JBOSS EAP
  hosts: webservers
  become: yes

  vars:
    eap_file: jboss-eap-7.0.0.zip
    jboss_user: jboss
    
  vars_files:
    - vars/application-config.yml

  roles:
    - { role: common, become: no }
    - jboss-standalone 
