# This playbook deploys the whole application stack in this site.


- name: Dynamically load hosts inventory
  hosts: localhost
  connection: local
  gather_facts: no
   
  vars_files:
    - vars/application-config.yml
    
  roles:
    - common
    - setup-hosts

- name: Setup DB
  hosts: dbservers
  #remote_user: virtuser

  vars_files:
    - vars/application-config.yml

  roles:
    - { role: common, become: no }
    - setup_db

- name: Deploy EAP application
  hosts: webservers
  become: yes
  #remote_user: virtuser
  
  vars_files:
    - vars/application-config.yml

  roles:
    - { role: common, become: no }
    - deploy-app


