- name: Load external password
  hosts: all
  connection: local
  gather_facts: no

  post_tasks:
    - name: "set password for the play"
      set_fact: ansible_ssh_pass="{{ lookup('firstpass', 'ssh') }}"
  
    - name: "set db_password for the play"
      set_fact: db_password="{{ lookup('firstpass', 'db') }}"
  
- name: Test whether password works
  hosts: all

  tasks:
    - debug: msg="db_password = {{ db_password }}"
    - ping: