{% for item in role_order %}

- name: Create temp directory to hold downloaded files
  shell: mktemp -d 
  register: script_tempdir    

- name: Download pre scripts {{item.name}}
  get_url:
    url: "{{app_script_url}}/{{ item.pre_script }}"
    dest: "{{ '{{' }} script_tempdir.stdout {{ '}}' }}"
  when: {{ item.run_pre_script }} and inventory_hostname in groups['{{item.name}}']

- name: Download post scripts {{ item.name }}
  get_url:
    url: "{{app_script_url}}/{{ item.post_script }}"
    dest: "{{ '{{' }} script_tempdir.stdout {{ '}}' }}"
  when: {{ item.run_post_script }} and inventory_hostname in groups['{{item.name}}']

- find:
    paths: "{{ '{{' }} script_tempdir.stdout {{ '}}' }}"
  register: scripts

- name: Set file permission  
  file:
    path: "{{ '{{' }} item.path {{ '}}' }}"
    mode: 0755
  with_items: "{{ '{{' }} scripts.files {{ '}}' }}"

- name: Running PRE script {{ item.name }}
  command: "{{ '{{' }} script_tempdir.stdout {{ '}}' }}/{{ item.pre_script }}"
  when: {{ item.run_pre_script }} and inventory_hostname in groups['{{item.name}}'] 

- name: Including Role {{ item.name }}
  include_role:
    name: {{ item.name }}
  when: inventory_hostname in groups['{{item.name}}']

- name: Running POST script {{ item.name }}
  command: "{{ '{{' }} script_tempdir.stdout {{ '}}' }}/{{ item.post_script }}"
  when: {{ item.run_post_script }} and inventory_hostname in groups['{{item.name}}'] 


###################

{% endfor %}