---
application_id: store
application_version: 1.0.0
load_module: true
module_file: modules.zip
load_ddl: true
ddl_file: import.sql
db_user: demouser
db_password: this.is.a.different.password # THIS IS DIFFERENT
startup_prop: startup.properties