---
# setup db

- name: Create demodb
  mysql_db:
    name: demodb
    state: present
    login_user: root

- debug: msg="DB user={{ db_user }} password={{ db_password }}"

- name: Create {{ db_user }} DB user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL'
    state: present
    host: "{{ item }}"
    login_user: root
  with_items:
    - "%"
    - "localhost"

- name: get DDL script
  get_url:
    url: "{{ nexus_repo_url }}/{{ application_id }}/{{ application_version }}/{{ ddl_file }}"
    dest: "/tmp/{{ ddl_file }}"
  when: (load_ddl is defined or load_ddl == true) and
        ddl_file is defined
  
- name: run DDL script
  shell: "mysql -u{{ db_user  }} -p{{ db_password }} demodb < /tmp/{{ ddl_file }}"
  #shell: "mysql -udemouser -ppassword.1234 demodb < /tmp/{{ ddl_file }}"
  when: (load_ddl is defined or load_ddl == true) and
        ddl_file is defined
 
