application_id: store
application_version: 1.0.0
load_module: true
module_file: modules.zip
load_ddl: true
db_hostname: 192.168.1.1
ddl_file: import.sql
db_user: demouser
db_password: password.1234
startup_prop: startup.properties
