---
- set_fact: 
    role_order: "{{ role_order|default([]) + \
                  [{ 'name': item.name, \
                     'pre_script': item.pre_script if item.pre_script is defined else None, \
                     'post_script': item.post_script if item.post_script is defined else None, \                     
                     'run_pre_script': True if item.pre_script is defined else False, \
                     'run_post_script': True if item.post_script is defined else False, \
                     'run_role': inventory_hostname in groups[item.name]} ] }}"
  with_items: "{{ module_order }}"
      
- block:
    # tempfile modile only available in ansible 2.3
    - name: Create temp directory to hold downloaded files
      shell: mktemp -d 
      register: tempdir    
      delegate_to: 127.0.0.1  

    - debug: msg="temp dir = {{ tempdir.stdout }}"
      delegate_to: 127.0.0.1  

    - debug: msg="Role order = {{ role_order }}"

    - template:
        src: insert-roles.yml
        dest: "{{ tempdir.stdout }}/insert-roles.yml"
      delegate_to: 127.0.0.1

    - include: "{{ tempdir.stdout }}/insert-roles.yml"
      static: no
    
  #rescue:
  
  always:
      - name: Clean up temp directory
        file: path="{{ tempdir.stdout }}" state=absent
        when: tempdir is defined
        delegate_to: 127.0.0.1



    
